### ISSUE TITLE
Mad flaps

### ISSUE THREAD

**Issue by kunaltyagi** [hczhcz/Flappy-2048#1]
Hold any key for a long time, else click like a maniac. Wait for the 'box' to go up up and beyond. Keep doing for say 5 seconds. leave. Enjoy the bouncing box.
Tap a key/click to return to normal behaviour.

Remove this bug man :)

**Comment by hczhcz** [comment]
The bouncing box is interesing to play with (I really love it now!!!) so I wont fix it.
